# Generated by Django 5.2.1 on 2025-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_entity_integrationlog_fielddefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date')], max_length=50),
        ),
    ]
